
// Type: BrightIdeasSoftware.HitTestLocationEx


// Hacked by SystemAce

using System;

namespace BrightIdeasSoftware
{
  [Flags]
  public enum HitTestLocationEx
  {
    LVHT_NOWHERE = 1,
    LVHT_ONITEMICON = 2,
    LVHT_ONITEMLABEL = 4,
    LVHT_ONITEMSTATEICON = 8,
    LVHT_ONITEM = LVHT_ONITEMSTATEICON | LVHT_ONITEMLABEL | LVHT_ONITEMICON,
    LVHT_ABOVE = LVHT_ONITEMSTATEICON,
    LVHT_BELOW = 16,
    LVHT_TORIGHT = 32,
    LVHT_TOLEFT = 64,
    LVHT_EX_GROUP_HEADER = 268435456,
    LVHT_EX_GROUP_FOOTER = 536870912,
    LVHT_EX_GROUP_COLLAPSE = 1073741824,
    LVHT_EX_GROUP_BACKGROUND = -2147483648,
    LVHT_EX_GROUP_STATEICON = 16777216,
    LVHT_EX_GROUP_SUBSETLINK = 33554432,
    LVHT_EX_GROUP = LVHT_EX_GROUP_SUBSETLINK | LVHT_EX_GROUP_STATEICON | LVHT_EX_GROUP_BACKGROUND | LVHT_EX_GROUP_COLLAPSE | LVHT_EX_GROUP_FOOTER | LVHT_EX_GROUP_HEADER,
    LVHT_EX_GROUP_MINUS_FOOTER_AND_BKGRD = LVHT_EX_GROUP_SUBSETLINK | LVHT_EX_GROUP_STATEICON | LVHT_EX_GROUP_COLLAPSE | LVHT_EX_GROUP_HEADER,
    LVHT_EX_ONCONTENTS = 67108864,
    LVHT_EX_FOOTER = 134217728,
  }
}
