
// Type: BrightIdeasSoftware.OLVColumn


// Hacked by SystemAce

using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Design;
using System.Windows.Forms;

namespace BrightIdeasSoftware
{
  [Browsable(false)]
  public class OLVColumn : ColumnHeader
  {
    private AutoCompleteMode autoCompleteEditorMode = AutoCompleteMode.Append;
    private bool groupable = true;
    private bool headerCheckBoxUpdatesRowCheckBoxes = true;
    private bool hideable = true;
    private bool isEditable = true;
    private bool isVisible = true;
    private int lastDisplayIndex = -1;
    private int maxWidth = -1;
    private int minWidth = -1;
    private bool searchable = true;
    private bool showTextInHeader = true;
    private bool sortable = true;
    private bool useFiltering = true;
    private IList valuesChosenForFiltering = (IList) new ArrayList();
    private AspectGetterDelegate aspectGetter;
    private bool aspectGetterAutoGenerated;
    private string aspectName;
    private AspectPutterDelegate aspectPutter;
    private AspectToStringConverterDelegate aspectToStringConverter;
    private string aspectToStringFormat;
    private Rectangle? cellPadding;
    private StringAlignment? cellVerticalAlignment;
    private bool checkBoxes;
    private IClusteringStrategy clusteringStrategy;
    private int freeSpaceProportion;
    private GroupFormatterDelegate groupFormatter;
    private GroupKeyGetterDelegate groupKeyGetter;
    private GroupKeyToTitleConverterDelegate groupKeyToTitleConverter;
    private string groupWithItemCountFormat;
    private string cachedGroupWithItemCountFormat;
    private string groupWithItemCountSingularFormat;
    private string cachedGroupWithItemCountSingularFormat;
    private HeaderDrawingDelegate headerDrawing;
    private HeaderFormatStyle headerFormatStyle;
    private string headerImageKey;
    private HorizontalAlignment? headerTextAlign;
    private bool headerCheckBox;
    private bool headerTriStateCheckBox;
    private CheckState headerCheckState;
    private bool headerCheckBoxDisabled;
    private bool hyperlink;
    private string imageAspectName;
    private ImageGetterDelegate imageGetter;
    private bool isTileViewColumn;
    private bool isHeaderVertical;
    private IRenderer renderer;
    private HorizontalAlignment? textAlign;
    private string toolTipText;
    private bool triStateCheckBoxes;
    private bool useInitialLetterForGroup;
    private IModelFilter valueBasedFilter;
    private bool wordWrap;
    private Munger aspectMunger;
    private Munger imageAspectMunger;
    private Type dataType;

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public AspectGetterDelegate AspectGetter
    {
      get
      {
        return this.aspectGetter;
      }
      set
      {
        this.aspectGetter = value;
      }
    }

    [Obsolete("This property is no longer maintained", true)]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public bool AspectGetterAutoGenerated
    {
      get
      {
        return this.aspectGetterAutoGenerated;
      }
      set
      {
        this.aspectGetterAutoGenerated = value;
      }
    }

    [Category("ObjectListView")]
    [Description("The name of the property or method that should be called to get the aspect to display in this column")]
    [DefaultValue(null)]
    public string AspectName
    {
      get
      {
        return this.aspectName;
      }
      set
      {
        this.aspectName = value;
        this.aspectMunger = (Munger) null;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public AspectPutterDelegate AspectPutter
    {
      get
      {
        return this.aspectPutter;
      }
      set
      {
        this.aspectPutter = value;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public AspectToStringConverterDelegate AspectToStringConverter
    {
      get
      {
        return this.aspectToStringConverter;
      }
      set
      {
        this.aspectToStringConverter = value;
      }
    }

    [Description("The format string that will be used to convert an aspect to its string representation")]
    [DefaultValue(null)]
    [Category("ObjectListView")]
    public string AspectToStringFormat
    {
      get
      {
        return this.aspectToStringFormat;
      }
      set
      {
        this.aspectToStringFormat = value;
      }
    }

    [DefaultValue(true)]
    [Category("ObjectListView")]
    [Description("Should the editor for cells of this column use AutoComplete")]
    public bool AutoCompleteEditor
    {
      get
      {
        return this.AutoCompleteEditorMode != AutoCompleteMode.None;
      }
      set
      {
        if (value)
        {
          if (this.AutoCompleteEditorMode != AutoCompleteMode.None)
            return;
          this.AutoCompleteEditorMode = AutoCompleteMode.Append;
        }
        else
          this.AutoCompleteEditorMode = AutoCompleteMode.None;
      }
    }

    [Category("ObjectListView")]
    [DefaultValue(AutoCompleteMode.Append)]
    [Description("Should the editor for cells of this column use AutoComplete")]
    public AutoCompleteMode AutoCompleteEditorMode
    {
      get
      {
        return this.autoCompleteEditorMode;
      }
      set
      {
        this.autoCompleteEditorMode = value;
      }
    }

    [Browsable(false)]
    public bool CanBeHidden
    {
      get
      {
        if (this.Hideable)
          return this.Index != 0;
        return false;
      }
    }

    [Category("ObjectListView")]
    [Description("How many pixels will be left blank around the cells in this column?")]
    [DefaultValue(null)]
    public Rectangle? CellPadding
    {
      get
      {
        return this.cellPadding;
      }
      set
      {
        this.cellPadding = value;
      }
    }

    [DefaultValue(null)]
    [Description("How will cell values be vertically aligned?")]
    [Category("ObjectListView")]
    public virtual StringAlignment? CellVerticalAlignment
    {
      get
      {
        return this.cellVerticalAlignment;
      }
      set
      {
        this.cellVerticalAlignment = value;
      }
    }

    [Description("Should values in this column be treated as a checkbox, rather than a string?")]
    [Category("ObjectListView")]
    [DefaultValue(false)]
    public virtual bool CheckBoxes
    {
      get
      {
        return this.checkBoxes;
      }
      set
      {
        if (this.checkBoxes == value)
          return;
        this.checkBoxes = value;
        if (this.checkBoxes)
        {
          if (this.Renderer != null)
            return;
          this.Renderer = (IRenderer) new CheckStateRenderer();
        }
        else
        {
          if (!(this.Renderer is CheckStateRenderer))
            return;
          this.Renderer = (IRenderer) null;
        }
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public IClusteringStrategy ClusteringStrategy
    {
      get
      {
        if (this.clusteringStrategy == null)
          this.ClusteringStrategy = this.DecideDefaultClusteringStrategy();
        return this.clusteringStrategy;
      }
      set
      {
        this.clusteringStrategy = value;
        if (this.clusteringStrategy == null)
          return;
        this.clusteringStrategy.Column = this;
      }
    }

    [Category("ObjectListView")]
    [Description("Will this column resize to fill unoccupied horizontal space in the listview?")]
    [DefaultValue(false)]
    public bool FillsFreeSpace
    {
      get
      {
        return this.FreeSpaceProportion > 0;
      }
      set
      {
        this.FreeSpaceProportion = value ? 1 : 0;
      }
    }

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    [Browsable(false)]
    public int FreeSpaceProportion
    {
      get
      {
        return this.freeSpaceProportion;
      }
      set
      {
        this.freeSpaceProportion = Math.Max(0, value);
      }
    }

    [Category("ObjectListView")]
    [Description("Will the list create groups when this header is clicked?")]
    [DefaultValue(true)]
    public bool Groupable
    {
      get
      {
        return this.groupable;
      }
      set
      {
        this.groupable = value;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public GroupFormatterDelegate GroupFormatter
    {
      get
      {
        return this.groupFormatter;
      }
      set
      {
        this.groupFormatter = value;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public GroupKeyGetterDelegate GroupKeyGetter
    {
      get
      {
        return this.groupKeyGetter;
      }
      set
      {
        this.groupKeyGetter = value;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public GroupKeyToTitleConverterDelegate GroupKeyToTitleConverter
    {
      get
      {
        return this.groupKeyToTitleConverter;
      }
      set
      {
        this.groupKeyToTitleConverter = value;
      }
    }

    [Description("The format to use when suffixing item counts to group titles")]
    [Localizable(true)]
    [Category("ObjectListView")]
    [DefaultValue(null)]
    public string GroupWithItemCountFormat
    {
      get
      {
        return this.groupWithItemCountFormat;
      }
      set
      {
        this.groupWithItemCountFormat = value;
      }
    }

    [Browsable(false)]
    public string GroupWithItemCountFormatOrDefault
    {
      get
      {
        if (!string.IsNullOrEmpty(this.GroupWithItemCountFormat))
          return this.GroupWithItemCountFormat;
        if (this.ListView == null)
          return this.cachedGroupWithItemCountFormat ?? "{0} [{1} items]";
        this.cachedGroupWithItemCountFormat = ((ObjectListView) this.ListView).GroupWithItemCountFormatOrDefault;
        return this.cachedGroupWithItemCountFormat;
      }
    }

    [Category("ObjectListView")]
    [Description("The format to use when suffixing item counts to group titles")]
    [Localizable(true)]
    [DefaultValue(null)]
    public string GroupWithItemCountSingularFormat
    {
      get
      {
        return this.groupWithItemCountSingularFormat;
      }
      set
      {
        this.groupWithItemCountSingularFormat = value;
      }
    }

    [Browsable(false)]
    public string GroupWithItemCountSingularFormatOrDefault
    {
      get
      {
        if (!string.IsNullOrEmpty(this.GroupWithItemCountSingularFormat))
          return this.GroupWithItemCountSingularFormat;
        if (this.ListView == null)
          return this.cachedGroupWithItemCountSingularFormat ?? "{0} [{1} item]";
        this.cachedGroupWithItemCountSingularFormat = ((ObjectListView) this.ListView).GroupWithItemCountSingularFormatOrDefault;
        return this.cachedGroupWithItemCountSingularFormat;
      }
    }

    [Browsable(false)]
    public bool HasFilterIndicator
    {
      get
      {
        if (this.UseFiltering && this.ValuesChosenForFiltering != null)
          return this.ValuesChosenForFiltering.Count > 0;
        return false;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public HeaderDrawingDelegate HeaderDrawing
    {
      get
      {
        return this.headerDrawing;
      }
      set
      {
        this.headerDrawing = value;
      }
    }

    [DefaultValue(null)]
    [Category("ObjectListView")]
    [Description("What style will be used to draw the header of this column")]
    public HeaderFormatStyle HeaderFormatStyle
    {
      get
      {
        return this.headerFormatStyle;
      }
      set
      {
        this.headerFormatStyle = value;
      }
    }

    [DefaultValue(null)]
    [Description("How will the header text be aligned?")]
    [Category("ObjectListView")]
    public Font HeaderFont
    {
      get
      {
        if (this.HeaderFormatStyle != null)
          return this.HeaderFormatStyle.Normal.Font;
        return (Font) null;
      }
      set
      {
        if (value == null && this.HeaderFormatStyle == null)
          return;
        if (this.HeaderFormatStyle == null)
          this.HeaderFormatStyle = new HeaderFormatStyle();
        this.HeaderFormatStyle.SetFont(value);
      }
    }

    [DefaultValue(typeof (Color), "")]
    [Description("How will the header text be aligned?")]
    [Category("ObjectListView")]
    public Color HeaderForeColor
    {
      get
      {
        if (this.HeaderFormatStyle != null)
          return this.HeaderFormatStyle.Normal.ForeColor;
        return Color.Empty;
      }
      set
      {
        if (value.IsEmpty && this.HeaderFormatStyle == null)
          return;
        if (this.HeaderFormatStyle == null)
          this.HeaderFormatStyle = new HeaderFormatStyle();
        this.HeaderFormatStyle.SetForeColor(value);
      }
    }

    [Description("Name of the image that will be shown in the column header.")]
    [DefaultValue(null)]
    [Category("ObjectListView")]
    [TypeConverter(typeof (ImageKeyConverter))]
    [Editor("System.Windows.Forms.Design.ImageIndexEditor, System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", typeof (UITypeEditor))]
    [RefreshProperties(RefreshProperties.Repaint)]
    public string HeaderImageKey
    {
      get
      {
        return this.headerImageKey;
      }
      set
      {
        this.headerImageKey = value;
      }
    }

    [Description("How will the header text be aligned?")]
    [DefaultValue(HorizontalAlignment.Left)]
    [Category("ObjectListView")]
    public HorizontalAlignment HeaderTextAlign
    {
      get
      {
        if (!this.headerTextAlign.HasValue)
          return this.TextAlign;
        return this.headerTextAlign.Value;
      }
      set
      {
        this.headerTextAlign = new HorizontalAlignment?(value);
      }
    }

    [Browsable(false)]
    public StringAlignment HeaderTextAlignAsStringAlignment
    {
      get
      {
        switch (this.HeaderTextAlign)
        {
          case HorizontalAlignment.Left:
            return StringAlignment.Near;
          case HorizontalAlignment.Right:
            return StringAlignment.Far;
          case HorizontalAlignment.Center:
            return StringAlignment.Center;
          default:
            return StringAlignment.Near;
        }
      }
    }

    [Browsable(false)]
    public bool HasHeaderImage
    {
      get
      {
        if (this.ListView != null && this.ListView.SmallImageList != null)
          return this.ListView.SmallImageList.Images.ContainsKey(this.HeaderImageKey);
        return false;
      }
    }

    [DefaultValue(false)]
    [Category("ObjectListView")]
    [Description("Draw a checkbox in the header of this column")]
    public bool HeaderCheckBox
    {
      get
      {
        return this.headerCheckBox;
      }
      set
      {
        this.headerCheckBox = value;
      }
    }

    [Description("Draw a tri-state checkbox in the header of this column")]
    [DefaultValue(false)]
    [Category("ObjectListView")]
    public bool HeaderTriStateCheckBox
    {
      get
      {
        return this.headerTriStateCheckBox;
      }
      set
      {
        this.headerTriStateCheckBox = value;
      }
    }

    [Category("ObjectListView")]
    [Description("Checkedness of the header checkbox")]
    [DefaultValue(CheckState.Unchecked)]
    public CheckState HeaderCheckState
    {
      get
      {
        return this.headerCheckState;
      }
      set
      {
        this.headerCheckState = value;
      }
    }

    [DefaultValue(true)]
    [Description("Update row checkboxs when the header checkbox is clicked by the user")]
    [Category("ObjectListView")]
    public bool HeaderCheckBoxUpdatesRowCheckBoxes
    {
      get
      {
        return this.headerCheckBoxUpdatesRowCheckBoxes;
      }
      set
      {
        this.headerCheckBoxUpdatesRowCheckBoxes = value;
      }
    }

    [DefaultValue(false)]
    [Category("ObjectListView")]
    [Description("Is the checkbox in the header of this column disabled")]
    public bool HeaderCheckBoxDisabled
    {
      get
      {
        return this.headerCheckBoxDisabled;
      }
      set
      {
        this.headerCheckBoxDisabled = value;
      }
    }

    [Category("ObjectListView")]
    [DefaultValue(true)]
    [Description("Will the user be able to choose to hide this column?")]
    public bool Hideable
    {
      get
      {
        return this.hideable;
      }
      set
      {
        this.hideable = value;
      }
    }

    [Category("ObjectListView")]
    [DefaultValue(false)]
    [Description("Will the text values in the cells of this column act like hyperlinks?")]
    public bool Hyperlink
    {
      get
      {
        return this.hyperlink;
      }
      set
      {
        this.hyperlink = value;
      }
    }

    [Category("ObjectListView")]
    [Description("The name of the property that holds the image selector")]
    [DefaultValue(null)]
    public string ImageAspectName
    {
      get
      {
        return this.imageAspectName;
      }
      set
      {
        this.imageAspectName = value;
      }
    }

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    [Browsable(false)]
    public ImageGetterDelegate ImageGetter
    {
      get
      {
        return this.imageGetter;
      }
      set
      {
        this.imageGetter = value;
      }
    }

    [Category("ObjectListView")]
    [Description("Can the value in this column be edited?")]
    [DefaultValue(true)]
    public bool IsEditable
    {
      get
      {
        return this.isEditable;
      }
      set
      {
        this.isEditable = value;
      }
    }

    [Browsable(false)]
    public bool IsFixedWidth
    {
      get
      {
        if (this.MinimumWidth != -1 && this.MaximumWidth != -1)
          return this.MinimumWidth >= this.MaximumWidth;
        return false;
      }
    }

    [DefaultValue(false)]
    [Description("Will this column be used when the view is switched to tile view")]
    [Category("ObjectListView")]
    public bool IsTileViewColumn
    {
      get
      {
        return this.isTileViewColumn;
      }
      set
      {
        this.isTileViewColumn = value;
      }
    }

    [Category("ObjectListView")]
    [Description("Will the header for this column be drawn vertically?")]
    [DefaultValue(false)]
    public bool IsHeaderVertical
    {
      get
      {
        return this.isHeaderVertical;
      }
      set
      {
        this.isHeaderVertical = value;
      }
    }

    [DefaultValue(true)]
    [Description("Can this column be seen by the user?")]
    [Category("ObjectListView")]
    public bool IsVisible
    {
      get
      {
        return this.isVisible;
      }
      set
      {
        if (this.isVisible == value)
          return;
        this.isVisible = value;
        this.OnVisibilityChanged(EventArgs.Empty);
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public int LastDisplayIndex
    {
      get
      {
        return this.lastDisplayIndex;
      }
      set
      {
        this.lastDisplayIndex = value;
      }
    }

    [Category("ObjectListView")]
    [DefaultValue(-1)]
    [Description("What is the maximum width to which the user can resize this column?")]
    public int MaximumWidth
    {
      get
      {
        return this.maxWidth;
      }
      set
      {
        this.maxWidth = value;
        if (this.maxWidth == -1 || this.Width <= this.maxWidth)
          return;
        this.Width = this.maxWidth;
      }
    }

    [Category("ObjectListView")]
    [Description("What is the minimum width to which the user can resize this column?")]
    [DefaultValue(-1)]
    public int MinimumWidth
    {
      get
      {
        return this.minWidth;
      }
      set
      {
        this.minWidth = value;
        if (this.Width >= this.minWidth)
          return;
        this.Width = this.minWidth;
      }
    }

    [Category("ObjectListView")]
    [Description("The renderer will draw this column when the ListView is owner drawn")]
    [DefaultValue(null)]
    public IRenderer Renderer
    {
      get
      {
        return this.renderer;
      }
      set
      {
        this.renderer = value;
      }
    }

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    [Browsable(false)]
    public RenderDelegate RendererDelegate
    {
      get
      {
        Version1Renderer version1Renderer = this.Renderer as Version1Renderer;
        if (version1Renderer == null)
          return (RenderDelegate) null;
        return version1Renderer.RenderDelegate;
      }
      set
      {
        this.Renderer = value == null ? (IRenderer) null : (IRenderer) new Version1Renderer(value);
      }
    }

    [DefaultValue(true)]
    [Category("ObjectListView")]
    [Description("Will the text of the cells in this column be considered when searching?")]
    public bool Searchable
    {
      get
      {
        return this.searchable;
      }
      set
      {
        this.searchable = value;
      }
    }

    [Category("ObjectListView")]
    [Description("Will the header for this column include text?")]
    [DefaultValue(true)]
    public bool ShowTextInHeader
    {
      get
      {
        return this.showTextInHeader;
      }
      set
      {
        this.showTextInHeader = value;
      }
    }

    [DefaultValue(true)]
    [Description("Will clicking this columns header resort the list?")]
    [Category("ObjectListView")]
    public bool Sortable
    {
      get
      {
        return this.sortable;
      }
      set
      {
        this.sortable = value;
      }
    }

    public new HorizontalAlignment TextAlign
    {
      get
      {
        if (!this.textAlign.HasValue)
          return base.TextAlign;
        return this.textAlign.Value;
      }
      set
      {
        this.textAlign = new HorizontalAlignment?(value);
        base.TextAlign = value;
      }
    }

    [Browsable(false)]
    public StringAlignment TextStringAlign
    {
      get
      {
        switch (this.TextAlign)
        {
          case HorizontalAlignment.Left:
            return StringAlignment.Near;
          case HorizontalAlignment.Right:
            return StringAlignment.Far;
          case HorizontalAlignment.Center:
            return StringAlignment.Center;
          default:
            return StringAlignment.Near;
        }
      }
    }

    [Category("ObjectListView")]
    [Description("The tooltip to show when the mouse is hovered over the header of this column")]
    [DefaultValue(null)]
    [Localizable(true)]
    public string ToolTipText
    {
      get
      {
        return this.toolTipText;
      }
      set
      {
        this.toolTipText = value;
      }
    }

    [Category("ObjectListView")]
    [Description("Should values in this column be treated as a tri-state checkbox?")]
    [DefaultValue(false)]
    public virtual bool TriStateCheckBoxes
    {
      get
      {
        return this.triStateCheckBoxes;
      }
      set
      {
        this.triStateCheckBoxes = value;
        if (!value || this.CheckBoxes)
          return;
        this.CheckBoxes = true;
      }
    }

    [DefaultValue(false)]
    [Description("The name of the property or method that should be called to get the aspect to display in this column")]
    [Category("ObjectListView")]
    public bool UseInitialLetterForGroup
    {
      get
      {
        return this.useInitialLetterForGroup;
      }
      set
      {
        this.useInitialLetterForGroup = value;
      }
    }

    [Description("Does this column want to show a Filter menu item when its header is right clicked")]
    [DefaultValue(true)]
    [Category("ObjectListView")]
    public bool UseFiltering
    {
      get
      {
        return this.useFiltering;
      }
      set
      {
        this.useFiltering = value;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public IModelFilter ValueBasedFilter
    {
      get
      {
        if (!this.UseFiltering)
          return (IModelFilter) null;
        if (this.valueBasedFilter != null)
          return this.valueBasedFilter;
        if (this.ClusteringStrategy == null)
          return (IModelFilter) null;
        if (this.ValuesChosenForFiltering == null || this.ValuesChosenForFiltering.Count == 0)
          return (IModelFilter) null;
        return this.ClusteringStrategy.CreateFilter(this.ValuesChosenForFiltering);
      }
      set
      {
        this.valueBasedFilter = value;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public IList ValuesChosenForFiltering
    {
      get
      {
        return this.valuesChosenForFiltering;
      }
      set
      {
        this.valuesChosenForFiltering = value;
      }
    }

    [Description("The width in pixels of this column")]
    [Category("ObjectListView")]
    [DefaultValue(60)]
    public new int Width
    {
      get
      {
        return base.Width;
      }
      set
      {
        if (this.MaximumWidth != -1 && value > this.MaximumWidth)
          base.Width = this.MaximumWidth;
        else
          base.Width = Math.Max(this.MinimumWidth, value);
      }
    }

    [DefaultValue(false)]
    [Category("ObjectListView")]
    [Description("Draw this column cell's word wrapped")]
    public bool WordWrap
    {
      get
      {
        return this.wordWrap;
      }
      set
      {
        this.wordWrap = value;
        if (this.Renderer == null && !this.wordWrap)
          return;
        if (this.Renderer == null)
          this.Renderer = (IRenderer) new HighlightTextRenderer();
        BaseRenderer baseRenderer = this.Renderer as BaseRenderer;
        if (baseRenderer == null)
          return;
        baseRenderer.CanWrap = this.wordWrap;
      }
    }

    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public Type DataType
    {
      get
      {
        if (this.dataType == (Type) null)
        {
          ObjectListView objectListView = this.ListView as ObjectListView;
          if (objectListView != null)
          {
            object firstNonNullValue = objectListView.GetFirstNonNullValue(this);
            if (firstNonNullValue != null)
              return firstNonNullValue.GetType();
          }
        }
        return this.dataType;
      }
      set
      {
        this.dataType = value;
      }
    }

    [Category("ObjectListView")]
    [Description("This event is triggered when the visibility of the column changes.")]
    public event EventHandler<EventArgs> VisibilityChanged;

    public OLVColumn()
    {
    }

    public OLVColumn(string title, string aspect)
      : this()
    {
      this.Text = title;
      this.AspectName = aspect;
    }

    public string ConvertGroupKeyToTitle(object value)
    {
      if (this.groupKeyToTitleConverter != null)
        return this.groupKeyToTitleConverter(value);
      if (value != null)
        return this.ValueToString(value);
      return ObjectListView.GroupTitleDefault;
    }

    public CheckState GetCheckState(object rowObject)
    {
      if (!this.CheckBoxes)
        return CheckState.Unchecked;
      bool? nullable = this.GetValue(rowObject) as bool?;
      if (!nullable.HasValue)
        return CheckState.Indeterminate;
      return nullable.Value ? CheckState.Checked : CheckState.Unchecked;
    }

    public void PutCheckState(object rowObject, CheckState newState)
    {
      if (newState == CheckState.Checked)
        this.PutValue(rowObject, (object) true);
      else if (newState == CheckState.Unchecked)
        this.PutValue(rowObject, (object) false);
      else
        this.PutValue(rowObject, (object) null);
    }

    public object GetAspectByName(object rowObject)
    {
      if (this.aspectMunger == null)
        this.aspectMunger = new Munger(this.AspectName);
      return this.aspectMunger.GetValue(rowObject);
    }

    public object GetGroupKey(object rowObject)
    {
      if (this.groupKeyGetter != null)
        return this.groupKeyGetter(rowObject);
      object obj = this.GetValue(rowObject);
      if (this.UseInitialLetterForGroup)
      {
        string str = obj as string;
        if (!string.IsNullOrEmpty(str))
          return (object) str.Substring(0, 1).ToUpper();
      }
      return obj;
    }

    public object GetImage(object rowObject)
    {
      if (this.CheckBoxes)
        return (object) this.GetCheckStateImage(rowObject);
      if (this.ImageGetter != null)
        return this.ImageGetter(rowObject);
      if (!string.IsNullOrEmpty(this.ImageAspectName))
      {
        if (this.imageAspectMunger == null)
          this.imageAspectMunger = new Munger(this.ImageAspectName);
        return this.imageAspectMunger.GetValue(rowObject);
      }
      if (!string.IsNullOrEmpty(this.ImageKey))
        return (object) this.ImageKey;
      return (object) this.ImageIndex;
    }

    public string GetCheckStateImage(object rowObject)
    {
      switch (this.GetCheckState(rowObject))
      {
        case CheckState.Checked:
          return "checkbox-checked";
        case CheckState.Unchecked:
          return "checkbox-unchecked";
        default:
          return "checkbox-indeterminate";
      }
    }

    public string GetStringValue(object rowObject)
    {
      return this.ValueToString(this.GetValue(rowObject));
    }

    public object GetValue(object rowObject)
    {
      if (this.AspectGetter == null)
        return this.GetAspectByName(rowObject);
      return this.AspectGetter(rowObject);
    }

    public void PutAspectByName(object rowObject, object newValue)
    {
      if (this.aspectMunger == null)
        this.aspectMunger = new Munger(this.AspectName);
      this.aspectMunger.PutValue(rowObject, newValue);
    }

    public void PutValue(object rowObject, object newValue)
    {
      if (this.aspectPutter == null)
        this.PutAspectByName(rowObject, newValue);
      else
        this.aspectPutter(rowObject, newValue);
    }

    public string ValueToString(object value)
    {
      if (this.AspectToStringConverter != null)
        return this.AspectToStringConverter(value) ?? string.Empty;
      if (value == null)
        return string.Empty;
      string aspectToStringFormat = this.AspectToStringFormat;
      if (string.IsNullOrEmpty(aspectToStringFormat))
        return value.ToString();
      return string.Format(aspectToStringFormat, value);
    }

    private IClusteringStrategy DecideDefaultClusteringStrategy()
    {
      if (!this.UseFiltering)
        return (IClusteringStrategy) null;
      if (this.DataType == typeof (DateTime))
        return (IClusteringStrategy) new DateTimeClusteringStrategy();
      return (IClusteringStrategy) new ClustersFromGroupsStrategy();
    }

    public virtual void OnVisibilityChanged(EventArgs e)
    {
      if (this.VisibilityChanged == null)
        return;
      this.VisibilityChanged((object) this, e);
    }

    public void MakeGroupies(object[] values, string[] descriptions)
    {
      this.MakeGroupies<object>(values, descriptions, (object[]) null, (string[]) null, (string[]) null);
    }

    public void MakeGroupies<T>(T[] values, string[] descriptions)
    {
      this.MakeGroupies<T>(values, descriptions, (object[]) null, (string[]) null, (string[]) null);
    }

    public void MakeGroupies<T>(T[] values, string[] descriptions, object[] images)
    {
      this.MakeGroupies<T>(values, descriptions, images, (string[]) null, (string[]) null);
    }

    public void MakeGroupies<T>(T[] values, string[] descriptions, object[] images, string[] subtitles)
    {
      this.MakeGroupies<T>(values, descriptions, images, subtitles, (string[]) null);
    }

    public void MakeGroupies<T>(T[] values, string[] descriptions, object[] images, string[] subtitles, string[] tasks)
    {
      if (values == null)
        throw new ArgumentNullException("values");
      if (descriptions == null)
        throw new ArgumentNullException("descriptions");
      if (values.Length + 1 != descriptions.Length)
        throw new ArgumentException("descriptions must have one more element than values.");
      this.GroupKeyGetter = (GroupKeyGetterDelegate) (row =>
      {
        object obj = this.GetValue(row);
        if (obj == null || obj == DBNull.Value)
          return (object) -1;
        IComparable comparable = (IComparable) obj;
        for (int index = 0; index < values.Length; ++index)
        {
          if (comparable.CompareTo((object) values[index]) < 0)
            return (object) index;
        }
        return (object) (descriptions.Length - 1);
      });
      this.GroupKeyToTitleConverter = (GroupKeyToTitleConverterDelegate) (key =>
      {
        if ((int) key < 0)
          return "";
        return descriptions[(int) key];
      });
      this.GroupFormatter = (GroupFormatterDelegate) ((group, parms) =>
      {
        int index = (int) group.Key;
        if (index < 0)
          return;
        if (images != null && index < images.Length)
          group.TitleImage = images[index];
        if (subtitles != null && index < subtitles.Length)
          group.Subtitle = subtitles[index];
        if (tasks == null || index >= tasks.Length)
          return;
        group.Task = tasks[index];
      });
    }

    public void MakeEqualGroupies<T>(T[] values, string[] descriptions, object[] images, string[] subtitles, string[] tasks)
    {
      if (values == null)
        throw new ArgumentNullException("values");
      if (descriptions == null)
        throw new ArgumentNullException("descriptions");
      if (values.Length != descriptions.Length)
        throw new ArgumentException("descriptions must have the same number of elements as values.");
      ArrayList valuesArray = new ArrayList((ICollection) values);
      this.GroupKeyGetter = (GroupKeyGetterDelegate) (row => (object) valuesArray.IndexOf(this.GetValue(row)));
      this.GroupKeyToTitleConverter = (GroupKeyToTitleConverterDelegate) (key =>
      {
        int index = (int) key;
        if (index >= 0)
          return descriptions[index];
        return "[other]";
      });
      this.GroupFormatter = (GroupFormatterDelegate) ((group, parms) =>
      {
        int index = (int) group.Key;
        if (index < 0)
          return;
        if (images != null && index < images.Length)
          group.TitleImage = images[index];
        if (subtitles != null && index < subtitles.Length)
          group.Subtitle = subtitles[index];
        if (tasks == null || index >= tasks.Length)
          return;
        group.Task = tasks[index];
      });
    }
  }
}
